FROM python:3.8.8-slim-buster

LABEL author="Rebecca" \
      version="1.0" \
      description="Image for cellranger ATAC"

# Create necessary directories
RUN mkdir -p /scripts /fastq /output /cellranger /references /opt/cellranger && \
    chmod -R 777 /scripts /fastq /output /cellranger /references /opt/cellranger

# Install cellranger
WORKDIR /opt/cellranger
COPY references/cellranger-atac-2.1.0.tar.gz /opt/cellranger
RUN tar -xzvf cellranger-atac-2.1.0.tar.gz \
    && rm cellranger-atac-2.1.0.tar.gz

# Download reference data
WORKDIR /references

COPY references/refdata-cellranger-arc-GRCh38-2020-A-2.0.0.tar.gz /references/

RUN tar -xzvf /references/refdata-cellranger-arc-GRCh38-2020-A-2.0.0.tar.gz \
    && rm /references/refdata-cellranger-arc-GRCh38-2020-A-2.0.0.tar.gz

# Set cellranger in PATH
ENV PATH="/opt/cellranger/cellranger-atac-2.1.0:$PATH"

# Copy all scripts
COPY scripts/* /scripts/
COPY scripts/pipeline_entrypoint.sh /scripts/

# Copy reference files if needed
COPY references/* /references/

# Make scripts executable and fix line endings
RUN chmod +x /scripts/*.sh && \
    sed -i 's/\r$//' /scripts/*.sh && \
    ln -sf /scripts/pipeline_entrypoint.sh /pipeline_entrypoint.sh

WORKDIR /output

ENTRYPOINT ["/scripts/pipeline_entrypoint.sh"]
CMD ["version"]